using System.Text;
using Xunit;
using SignalWire.SWML;
using SignalWire.Logging;

namespace SignalWire.Tests;

public class SWMLServiceTests : IDisposable
{
    public SWMLServiceTests()
    {
        Schema.Reset();
        Logger.Reset();
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_USER", null);
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_PASSWORD", null);
        Environment.SetEnvironmentVariable("SWML_PROXY_URL_BASE", null);
        Environment.SetEnvironmentVariable("PORT", null);
    }

    public void Dispose()
    {
        Schema.Reset();
        Logger.Reset();
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_USER", null);
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_PASSWORD", null);
        Environment.SetEnvironmentVariable("SWML_PROXY_URL_BASE", null);
        Environment.SetEnvironmentVariable("PORT", null);
    }

    private static Service MakeService(
        string name = "test-service",
        string? route = null,
        string? host = null,
        int? port = null,
        string? basicAuthUser = "testuser",
        string? basicAuthPassword = "testpass")
    {
        return new Service(new ServiceOptions
        {
            Name = name,
            Route = route ?? "/",
            Host = host ?? "0.0.0.0",
            Port = port,
            BasicAuthUser = basicAuthUser,
            BasicAuthPassword = basicAuthPassword,
        });
    }

    private static Dictionary<string, string> AuthHeader(string user = "testuser", string pass = "testpass")
    {
        var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{user}:{pass}"));
        return new Dictionary<string, string> { ["Authorization"] = $"Basic {encoded}" };
    }

    // ------------------------------------------------------------------
    // Construction
    // ------------------------------------------------------------------

    [Fact]
    public void Construction_Defaults()
    {
        var svc = MakeService();
        Assert.Equal("test-service", svc.Name);
        Assert.Equal("/", svc.Route);
        Assert.Equal("0.0.0.0", svc.Host);
        Assert.Equal(3000, svc.Port);
    }

    [Fact]
    public void CustomRoute()
    {
        var svc = MakeService(route: "/myagent");
        Assert.Equal("/myagent", svc.Route);
    }

    [Fact]
    public void TrailingSlash_Stripped()
    {
        var svc = MakeService(route: "/myagent/");
        Assert.Equal("/myagent", svc.Route);
    }

    [Fact]
    public void Port_FromEnv()
    {
        Environment.SetEnvironmentVariable("PORT", "8080");
        var svc = new Service(new ServiceOptions
        {
            Name = "test",
            BasicAuthUser = "u",
            BasicAuthPassword = "p",
        });
        Assert.Equal(8080, svc.Port);
    }

    // ------------------------------------------------------------------
    // Auth
    // ------------------------------------------------------------------

    [Fact]
    public void ExplicitAuth()
    {
        var svc = MakeService(basicAuthUser: "myuser", basicAuthPassword: "mypass");
        var (user, pass) = svc.GetBasicAuthCredentials();
        Assert.Equal("myuser", user);
        Assert.Equal("mypass", pass);
    }

    [Fact]
    public void EnvAuth()
    {
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_USER", "envuser");
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_PASSWORD", "envpass");
        var svc = new Service(new ServiceOptions { Name = "test" });
        var (user, pass) = svc.GetBasicAuthCredentials();
        Assert.Equal("envuser", user);
        Assert.Equal("envpass", pass);
    }

    [Fact]
    public void AutoGeneratedAuth()
    {
        var svc = new Service(new ServiceOptions { Name = "test" });
        var (user, pass) = svc.GetBasicAuthCredentials();
        Assert.NotEmpty(user);
        Assert.NotEmpty(pass);
        Assert.True(user.Length > 8);
        Assert.True(pass.Length > 8);
    }

    [Fact]
    public void AutoGeneratedAuth_DifferentEachTime()
    {
        var svc1 = new Service(new ServiceOptions { Name = "test1" });
        var svc2 = new Service(new ServiceOptions { Name = "test2" });
        var (user1, _) = svc1.GetBasicAuthCredentials();
        var (user2, _) = svc2.GetBasicAuthCredentials();
        Assert.NotEqual(user1, user2);
    }

    [Fact]
    public void GetFullUrl_WithoutAuth()
    {
        var svc = MakeService();
        Assert.Equal("http://0.0.0.0:3000/", svc.GetFullUrl());
    }

    [Fact]
    public void GetFullUrl_WithAuth()
    {
        var svc = MakeService(basicAuthUser: "u", basicAuthPassword: "p");
        Assert.Equal("http://u:p@0.0.0.0:3000/", svc.GetFullUrl(includeAuth: true));
    }

    [Fact]
    public void GetFullUrl_WithRoute()
    {
        var svc = MakeService(route: "/agent");
        Assert.Equal("http://0.0.0.0:3000/agent", svc.GetFullUrl());
    }

    // ------------------------------------------------------------------
    // Verb methods
    // ------------------------------------------------------------------

    [Fact]
    public void Verb_AddsToDocument()
    {
        var svc = MakeService();
        svc.Verb("answer", new Dictionary<string, object> { ["max_duration"] = 3600 });

        var verbs = svc.Document.GetVerbs("main");
        Assert.Single(verbs);
        Assert.True(verbs[0].ContainsKey("answer"));
    }

    [Fact]
    public void Sleep_TakesInteger()
    {
        var svc = MakeService();
        svc.Sleep(2000);

        var verbs = svc.Document.GetVerbs("main");
        Assert.Single(verbs);
        Assert.True(verbs[0].ContainsKey("sleep"));
        Assert.Equal(2000, verbs[0]["sleep"]);
    }

    [Fact]
    public void Verb_Chaining()
    {
        var svc = MakeService();
        var result = svc.Verb("answer", new Dictionary<string, object> { ["max_duration"] = 3600 });
        Assert.Same(svc, result);
    }

    [Fact]
    public void AllSchemaVerbs_Callable()
    {
        var svc = MakeService();
        var schema = Schema.Instance;
        var names = schema.GetVerbNames();

        foreach (var verb in names)
        {
            if (verb == "sleep")
            {
                svc.Sleep(1000);
            }
            else
            {
                svc.Verb(verb, new Dictionary<string, object>());
            }
        }

        var verbs = svc.Document.GetVerbs("main");
        Assert.Equal(names.Count, verbs.Count);
    }

    [Fact]
    public void UnknownVerb_Throws()
    {
        var svc = MakeService();
        Assert.Throws<ArgumentException>(() => svc.Verb("nonexistent_verb", new Dictionary<string, object>()));
    }

    // ------------------------------------------------------------------
    // HTTP: Health / Ready
    // ------------------------------------------------------------------

    [Fact]
    public void Health_Returns200_NoAuth()
    {
        var svc = MakeService();
        var (status, headers, body) = svc.HandleRequest("GET", "/health", new Dictionary<string, string>(), null);

        Assert.Equal(200, status);
        Assert.Equal("application/json", headers["Content-Type"]);
        Assert.Contains("healthy", body);
    }

    [Fact]
    public void Ready_Returns200_NoAuth()
    {
        var svc = MakeService();
        var (status, _, body) = svc.HandleRequest("GET", "/ready", new Dictionary<string, string>(), null);

        Assert.Equal(200, status);
        Assert.Contains("ready", body);
    }

    // ------------------------------------------------------------------
    // HTTP: Auth
    // ------------------------------------------------------------------

    [Fact]
    public void Root_WithoutAuth_Returns401()
    {
        var svc = MakeService();
        var (status, headers, _) = svc.HandleRequest("GET", "/", new Dictionary<string, string>(), null);

        Assert.Equal(401, status);
        Assert.True(headers.ContainsKey("WWW-Authenticate"));
    }

    [Fact]
    public void Root_WithCorrectAuth_Returns200Swml()
    {
        var svc = MakeService();
        var (status, _, body) = svc.HandleRequest("GET", "/", AuthHeader(), null);

        Assert.Equal(200, status);
        Assert.Contains("1.0.0", body);
    }

    [Fact]
    public void WrongPassword_Returns401()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("GET", "/", AuthHeader("testuser", "wrongpass"), null);
        Assert.Equal(401, status);
    }

    [Fact]
    public void WrongUser_Returns401()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("GET", "/", AuthHeader("wronguser", "testpass"), null);
        Assert.Equal(401, status);
    }

    // ------------------------------------------------------------------
    // HTTP: Security Headers
    // ------------------------------------------------------------------

    [Fact]
    public void SecurityHeaders_Present_OnAuthenticatedResponse()
    {
        var svc = MakeService();
        var (status, headers, _) = svc.HandleRequest("GET", "/", AuthHeader(), null);

        Assert.Equal(200, status);
        Assert.Equal("nosniff", headers["X-Content-Type-Options"]);
        Assert.Equal("DENY", headers["X-Frame-Options"]);
        Assert.Equal("no-store", headers["Cache-Control"]);
    }

    [Fact]
    public void SecurityHeaders_Present_On401()
    {
        var svc = MakeService();
        var (_, headers, _) = svc.HandleRequest("GET", "/", new Dictionary<string, string>(), null);

        Assert.Equal("nosniff", headers["X-Content-Type-Options"]);
        Assert.Equal("DENY", headers["X-Frame-Options"]);
        Assert.Equal("no-store", headers["Cache-Control"]);
    }

    // ------------------------------------------------------------------
    // HTTP: /swaig and /post_prompt require auth
    // ------------------------------------------------------------------

    [Fact]
    public void Swaig_WithoutAuth_Returns401()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("POST", "/swaig", new Dictionary<string, string>(), null);
        Assert.Equal(401, status);
    }

    [Fact]
    public void Swaig_WithAuth_Returns200()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("POST", "/swaig", AuthHeader(), "{}");
        Assert.Equal(200, status);
    }

    [Fact]
    public void PostPrompt_WithoutAuth_Returns401()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("POST", "/post_prompt", new Dictionary<string, string>(), null);
        Assert.Equal(401, status);
    }

    [Fact]
    public void PostPrompt_WithAuth_Returns200()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("POST", "/post_prompt", AuthHeader(), "{}");
        Assert.Equal(200, status);
    }

    // ------------------------------------------------------------------
    // HTTP: Custom Route Dispatch
    // ------------------------------------------------------------------

    [Fact]
    public void CustomRoute_SwmlDispatch()
    {
        var svc = MakeService(route: "/agent");
        svc.Verb("hangup", new Dictionary<string, object>());

        var (status, _, body) = svc.HandleRequest("GET", "/agent", AuthHeader(), null);
        Assert.Equal(200, status);
        Assert.Contains("hangup", body);
    }

    [Fact]
    public void CustomRoute_SwaigDispatch()
    {
        var svc = MakeService(route: "/agent");
        var (status, _, _) = svc.HandleRequest("POST", "/agent/swaig", AuthHeader(), "{}");
        Assert.Equal(200, status);
    }

    [Fact]
    public void CustomRoute_HealthStillWorks()
    {
        var svc = MakeService(route: "/agent");
        var (status, _, _) = svc.HandleRequest("GET", "/health", new Dictionary<string, string>(), null);
        Assert.Equal(200, status);
    }

    [Fact]
    public void UnmatchedRoute_Returns404()
    {
        var svc = MakeService(route: "/agent");
        var (status, _, _) = svc.HandleRequest("GET", "/other", AuthHeader(), null);
        Assert.Equal(404, status);
    }

    // ------------------------------------------------------------------
    // HTTP: Body Size Limit
    // ------------------------------------------------------------------

    [Fact]
    public void BodySizeLimit_1MBPlus1Byte_Returns413()
    {
        var svc = MakeService();
        var hugeBody = new string('x', 1_048_577); // 1MB + 1 byte
        var (status, _, _) = svc.HandleRequest("POST", "/", AuthHeader(), hugeBody);
        Assert.Equal(413, status);
    }

    // ------------------------------------------------------------------
    // SIP Username Extraction
    // ------------------------------------------------------------------

    [Fact]
    public void ExtractSipUsername_ValidUri()
    {
        var body = new Dictionary<string, object>
        {
            ["call"] = new Dictionary<string, object> { ["to"] = "sip:agent1@example.com" },
        };
        Assert.Equal("agent1", Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_FromTopLevelTo()
    {
        var body = new Dictionary<string, object> { ["to"] = "sip:myuser@host.com" };
        Assert.Equal("myuser", Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_ValidChars()
    {
        var body = new Dictionary<string, object> { ["to"] = "sip:user.name-test_1@host.com" };
        Assert.Equal("user.name-test_1", Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_InvalidChars_ReturnsNull()
    {
        var body = new Dictionary<string, object> { ["to"] = "sip:user;drop@host.com" };
        Assert.Null(Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_TooLong_ReturnsNull()
    {
        var longName = new string('a', 65);
        var body = new Dictionary<string, object> { ["to"] = $"sip:{longName}@host.com" };
        Assert.Null(Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_Null_ReturnsNull()
    {
        Assert.Null(Service.ExtractSipUsername(null));
    }

    [Fact]
    public void ExtractSipUsername_EmptyBody_ReturnsNull()
    {
        Assert.Null(Service.ExtractSipUsername(new Dictionary<string, object>()));
    }

    // ------------------------------------------------------------------
    // Proxy URL
    // ------------------------------------------------------------------

    [Fact]
    public void ProxyUrl_FromEnv()
    {
        Environment.SetEnvironmentVariable("SWML_PROXY_URL_BASE", "https://proxy.example.com");
        var svc = MakeService();
        Assert.Equal("https://proxy.example.com", svc.GetProxyUrlBase());
    }

    [Fact]
    public void ProxyUrl_FromForwardedHeaders()
    {
        var svc = MakeService();
        var headers = new Dictionary<string, string>
        {
            ["X-Forwarded-Proto"] = "https",
            ["X-Forwarded-Host"] = "myapp.example.com",
        };
        Assert.Equal("https://myapp.example.com", svc.GetProxyUrlBase(headers));
    }

    [Fact]
    public void ProxyUrl_FromOriginalUrl()
    {
        var svc = MakeService();
        var headers = new Dictionary<string, string>
        {
            ["X-Original-URL"] = "https://original.example.com/path",
        };
        Assert.Equal("https://original.example.com/path", svc.GetProxyUrlBase(headers));
    }

    [Fact]
    public void ProxyUrl_Fallback()
    {
        var svc = MakeService(host: "0.0.0.0", port: 3000);
        Assert.Equal("http://0.0.0.0:3000", svc.GetProxyUrlBase());
    }

    // ------------------------------------------------------------------
    // Routing Callbacks
    // ------------------------------------------------------------------

    [Fact]
    public void RoutingCallback_Dispatched()
    {
        var svc = MakeService();
        var called = false;
        svc.RegisterRoutingCallback("/custom", (data, headers) =>
        {
            called = true;
            return new Dictionary<string, object> { ["custom"] = "response" };
        });

        var (status, _, body) = svc.HandleRequest("POST", "/custom", AuthHeader(), "{}");
        Assert.True(called);
        Assert.Equal(200, status);
        Assert.Contains("response", body);
    }
}
