using System.Text;
using Xunit;
using SignalWire.SWML;
using SignalWire.Logging;

namespace SignalWire.Tests;

[Collection(GlobalStateCollection.Name)]
public sealed class SWMLServiceTests : IDisposable
{
    public SWMLServiceTests()
    {
        Schema.Reset();
        Logger.Reset();
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_USER", null);
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_PASSWORD", null);
        Environment.SetEnvironmentVariable("SWML_PROXY_URL_BASE", null);
        Environment.SetEnvironmentVariable("PORT", null);
    }

    public void Dispose()
    {
        Schema.Reset();
        Logger.Reset();
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_USER", null);
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_PASSWORD", null);
        Environment.SetEnvironmentVariable("SWML_PROXY_URL_BASE", null);
        Environment.SetEnvironmentVariable("PORT", null);
    }

    private static Service MakeService(
        string name = "test-service",
        string? route = null,
        string? host = null,
        int? port = null,
        string? basicAuthUser = "testuser",
        string? basicAuthPassword = "testpass")
    {
        return new Service(new ServiceOptions
        {
            Name = name,
            Route = route ?? "/",
            Host = host ?? "0.0.0.0",
            Port = port,
            BasicAuthUser = basicAuthUser,
            BasicAuthPassword = basicAuthPassword,
        });
    }

    private static Dictionary<string, string> AuthHeader(string user = "testuser", string pass = "testpass")
    {
        var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{user}:{pass}"));
        return new Dictionary<string, string> { ["Authorization"] = $"Basic {encoded}" };
    }

    // ------------------------------------------------------------------
    // Construction
    // ------------------------------------------------------------------

    [Fact]
    public void Construction_Defaults()
    {
        var svc = MakeService();
        Assert.Equal("test-service", svc.Name);
        Assert.Equal("/", svc.Route);
        Assert.Equal("0.0.0.0", svc.Host);
        Assert.Equal(3000, svc.Port);
    }

    [Fact]
    public void CustomRoute()
    {
        var svc = MakeService(route: "/myagent");
        Assert.Equal("/myagent", svc.Route);
    }

    [Fact]
    public void TrailingSlash_Stripped()
    {
        var svc = MakeService(route: "/myagent/");
        Assert.Equal("/myagent", svc.Route);
    }

    [Fact]
    public void Port_FromEnv()
    {
        Environment.SetEnvironmentVariable("PORT", "8080");
        var svc = new Service(new ServiceOptions
        {
            Name = "test",
            BasicAuthUser = "u",
            BasicAuthPassword = "p",
        });
        Assert.Equal(8080, svc.Port);
    }

    // ------------------------------------------------------------------
    // Auth
    // ------------------------------------------------------------------

    [Fact]
    public void ExplicitAuth()
    {
        var svc = MakeService(basicAuthUser: "myuser", basicAuthPassword: "mypass");
        var (user, pass) = svc.GetBasicAuthCredentials();
        Assert.Equal("myuser", user);
        Assert.Equal("mypass", pass);
    }

    [Fact]
    public void EnvAuth()
    {
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_USER", "envuser");
        Environment.SetEnvironmentVariable("SWML_BASIC_AUTH_PASSWORD", "envpass");
        var svc = new Service(new ServiceOptions { Name = "test" });
        var (user, pass) = svc.GetBasicAuthCredentials();
        Assert.Equal("envuser", user);
        Assert.Equal("envpass", pass);
    }

    [Fact]
    public void AutoGeneratedAuth()
    {
        var svc = new Service(new ServiceOptions { Name = "test" });
        var (user, pass) = svc.GetBasicAuthCredentials();
        Assert.NotEmpty(user);
        Assert.NotEmpty(pass);
        Assert.True(user.Length > 8);
        Assert.True(pass.Length > 8);
    }

    [Fact]
    public void AutoGeneratedAuth_DifferentEachTime()
    {
        var svc1 = new Service(new ServiceOptions { Name = "test1" });
        var svc2 = new Service(new ServiceOptions { Name = "test2" });
        var (user1, _) = svc1.GetBasicAuthCredentials();
        var (user2, _) = svc2.GetBasicAuthCredentials();
        Assert.NotEqual(user1, user2);
    }

    [Fact]
    public void GetFullUrl_WithoutAuth()
    {
        var svc = MakeService();
        Assert.Equal("http://0.0.0.0:3000/", svc.GetFullUrl());
    }

    [Fact]
    public void GetFullUrl_WithAuth()
    {
        var svc = MakeService(basicAuthUser: "u", basicAuthPassword: "p");
        Assert.Equal("http://u:p@0.0.0.0:3000/", svc.GetFullUrl(includeAuth: true));
    }

    [Fact]
    public void GetFullUrl_WithRoute()
    {
        var svc = MakeService(route: "/agent");
        Assert.Equal("http://0.0.0.0:3000/agent", svc.GetFullUrl());
    }

    // ------------------------------------------------------------------
    // Verb methods
    // ------------------------------------------------------------------

    [Fact]
    public void Verb_AddsToDocument()
    {
        var svc = MakeService();
        svc.Verb("answer", new Dictionary<string, object> { ["max_duration"] = 3600 });

        var verbs = svc.Document.GetVerbs("main");
        Assert.Single(verbs);
        Assert.True(verbs[0].ContainsKey("answer"));
    }

    [Fact]
    public void Sleep_TakesInteger()
    {
        var svc = MakeService();
        svc.Sleep(2000);

        var verbs = svc.Document.GetVerbs("main");
        Assert.Single(verbs);
        Assert.True(verbs[0].ContainsKey("sleep"));
        Assert.Equal(2000, verbs[0]["sleep"]);
    }

    [Fact]
    public void Verb_Chaining()
    {
        var svc = MakeService();
        var result = svc.Verb("answer", new Dictionary<string, object> { ["max_duration"] = 3600 });
        Assert.Same(svc, result);
    }

    /// <summary>
    /// Minimal schema-VALID configs for the verbs whose <c>$defs</c> entry
    /// declares required fields. Every other verb accepts an empty object.
    /// </summary>
    /// <summary>
    /// Verbs whose schema config is NOT an object (an array, a string, or a
    /// scalar). The validating entry point takes <c>dict | int</c> and
    /// special-cases only <c>sleep</c>'s bare integer — exactly as the reference
    /// does (<c>swml_service.py:534</c> <c>add_verb(verb_name, config: dict | int)</c>,
    /// which rejects any other non-dict). So these verbs are not reachable
    /// through the validating path in EITHER implementation; they are excluded
    /// from the name-callability sweep rather than papered over with a config
    /// the schema would reject anyway.
    /// </summary>
    private static readonly HashSet<string> NonObjectConfigVerbs =
    [
        "cond", "unset", "label", "change_context", "change_step",
        "toggle_functions", "user_input", "say",
    ];

    private static readonly Dictionary<string, Dictionary<string, object>> MinimalValidConfigs = new()
    {
        ["ai"] = new() { ["prompt"] = new Dictionary<string, object> { ["text"] = "hi" } },
        ["ai_sidecar"] = new() { ["prompt"] = "hi", ["lang"] = "en-US" },
        ["amazon_bedrock"] = new() { ["prompt"] = new Dictionary<string, object> { ["text"] = "hi" } },
        ["connect"] = new() { ["to"] = "sip:someone@example.com" },
        ["context_switch"] = new() { ["system_prompt"] = "hi" },
        ["enter_queue"] = new() { ["queue_name"] = "q1", ["transfer_after_bridge"] = "main" },
        ["join_conference"] = new() { ["name"] = "conf1" },
        ["play"] = new() { ["url"] = "say:hello" },
        ["send_sms"] = new()
        {
            ["to_number"] = "+15550001111",
            ["from_number"] = "+15550002222",
            ["body"] = "hi",
        },
        ["execute"] = new() { ["dest"] = "other_section" },
        ["goto"] = new() { ["label"] = "top" },
        ["inject"] = new() { ["direction"] = "remote-caller", ["message"] = "hi" },
        ["join_room"] = new() { ["name"] = "room1" },
        ["live_transcribe"] = new() { ["action"] = "stop" },
        ["live_translate"] = new() { ["action"] = "stop" },
        ["pay"] = new() { ["payment_connector_url"] = "https://example.com/pay" },
        ["playback_bg"] = new() { ["file"] = "https://example.com/bg.mp3" },
        ["prompt"] = new() { ["play"] = "say:pick one" },
        ["request"] = new() { ["method"] = "GET", ["url"] = "https://example.com/x" },
        ["send_digits"] = new() { ["digits"] = "123" },
        ["send_fax"] = new() { ["document"] = "https://example.com/f.pdf" },
        ["sip_refer"] = new() { ["to_uri"] = "sip:someone@example.com" },
        ["start"] = new()
        {
            ["direction"] = "remote-caller",
            ["lang"] = "en-US",
            ["from_lang"] = "en-US",
            ["to_lang"] = "es-ES",
        },
        ["switch"] = new()
        {
            ["variable"] = "digits",
            ["case"] = new Dictionary<string, object>(),
        },
        ["tap"] = new() { ["uri"] = "wss://example.com/tap" },
        ["transfer"] = new() { ["dest"] = "sip:someone@example.com" },
        ["user_event"] = new() { ["event"] = new Dictionary<string, object>() },
    };

    [Fact]
    public void AllSchemaVerbs_Callable()
    {
        var svc = MakeService();
        var schema = Schema.Instance;
        var names = schema.GetVerbNames();

        foreach (var verb in names)
        {
            if (verb == "sleep")
            {
                svc.Sleep(1000);
            }
            else if (NonObjectConfigVerbs.Contains(verb))
            {
                continue;
            }
            else if (MinimalValidConfigs.TryGetValue(verb, out var minimal))
            {
                // Verb() now validates the CONFIG, not just the verb name, so
                // the verbs whose schema declares required fields need those
                // fields supplied. An empty config is legitimately rejected.
                svc.Verb(verb, minimal);
            }
            else
            {
                svc.Verb(verb, new Dictionary<string, object>());
            }
        }

        var verbs = svc.Document.GetVerbs("main");
        var expected = names.Count(n => !NonObjectConfigVerbs.Contains(n));
        Assert.Equal(expected, verbs.Count);
        Assert.True(expected > 0);
    }

    [Fact]
    public void UnknownVerb_Throws()
    {
        var svc = MakeService();
        Assert.Throws<ArgumentException>(() => svc.Verb("nonexistent_verb", new Dictionary<string, object>()));
    }

    // ------------------------------------------------------------------
    // HTTP: Health / Ready
    // ------------------------------------------------------------------

    [Fact]
    public void Health_Returns200_NoAuth()
    {
        var svc = MakeService();
        var (status, headers, body) = svc.HandleRequest("GET", "/health", new Dictionary<string, string>(), null);

        Assert.Equal(200, status);
        Assert.Equal("application/json", headers["Content-Type"]);
        Assert.Contains("healthy", body);
    }

    [Fact]
    public void Ready_Returns200_NoAuth()
    {
        var svc = MakeService();
        var (status, _, body) = svc.HandleRequest("GET", "/ready", new Dictionary<string, string>(), null);

        Assert.Equal(200, status);
        Assert.Contains("ready", body);
    }

    // ------------------------------------------------------------------
    // AsRouter: mountable host-app handler (Python parity: WebMixin.as_router /
    // SWMLService.as_router). The returned RequestDelegate embeds the service's
    // routes in a host ASP.NET Core app; driving an HttpContext through it must
    // dispatch the same logic as HandleRequest.
    // ------------------------------------------------------------------

    private static async Task<(int Status, string Body, Microsoft.AspNetCore.Http.HttpContext Ctx)> DriveRouterAsync(
        Microsoft.AspNetCore.Http.RequestDelegate router,
        string method,
        string path,
        string? authHeader = null,
        string? body = null)
    {
        var ctx = new Microsoft.AspNetCore.Http.DefaultHttpContext();
        ctx.Request.Method = method;
        ctx.Request.Path = path;
        if (authHeader is not null)
        {
            ctx.Request.Headers["Authorization"] = authHeader;
        }
        if (body is not null)
        {
            ctx.Request.Body = new MemoryStream(Encoding.UTF8.GetBytes(body));
        }
        var responseStream = new MemoryStream();
        ctx.Response.Body = responseStream;

        await router(ctx).ConfigureAwait(false);

        responseStream.Position = 0;
        using var reader = new StreamReader(responseStream, Encoding.UTF8);
        var text = await reader.ReadToEndAsync().ConfigureAwait(false);
        return (ctx.Response.StatusCode, text, ctx);
    }

    [Fact]
    public void AsRouter_ReturnsRequestDelegate()
    {
        var svc = MakeService();
        Microsoft.AspNetCore.Http.RequestDelegate router = svc.AsRouter();
        Assert.NotNull(router);
    }

    [Fact]
    public async Task AsRouter_Health_Returns200_NoAuth()
    {
        var svc = MakeService();
        var (status, body, _) = await DriveRouterAsync(svc.AsRouter(), "GET", "/health");

        Assert.Equal(200, status);
        Assert.Contains("healthy", body);
    }

    [Fact]
    public async Task AsRouter_Root_WithoutAuth_Returns401()
    {
        var svc = MakeService();
        var (status, _, ctx) = await DriveRouterAsync(svc.AsRouter(), "GET", "/");

        Assert.Equal(401, status);
        Assert.True(ctx.Response.Headers.ContainsKey("WWW-Authenticate"));
    }

    [Fact]
    public async Task AsRouter_Root_WithAuth_ReturnsSwml()
    {
        var svc = MakeService();
        var auth = "Basic " + Convert.ToBase64String(Encoding.UTF8.GetBytes("testuser:testpass"));
        var (status, body, _) = await DriveRouterAsync(svc.AsRouter(), "GET", "/", authHeader: auth);

        Assert.Equal(200, status);
        Assert.Contains("version", body); // rendered SWML document
    }

    [Fact]
    public async Task AsRouter_MatchesHandleRequest()
    {
        // The mounted handler must dispatch the identical logic as the standalone
        // HandleRequest path — same status + body for the same request.
        var svc = MakeService();
        var (directStatus, _, directBody) = svc.HandleRequest(
            "GET", "/health", new Dictionary<string, string>(), null);
        var (routerStatus, routerBody, _) = await DriveRouterAsync(svc.AsRouter(), "GET", "/health");

        Assert.Equal(directStatus, routerStatus);
        Assert.Equal(directBody, routerBody);
    }

    // ------------------------------------------------------------------
    // HTTP: Auth
    // ------------------------------------------------------------------

    [Fact]
    public void Root_WithoutAuth_Returns401()
    {
        var svc = MakeService();
        var (status, headers, _) = svc.HandleRequest("GET", "/", new Dictionary<string, string>(), null);

        Assert.Equal(401, status);
        Assert.True(headers.ContainsKey("WWW-Authenticate"));
    }

    [Fact]
    public void Root_WithCorrectAuth_Returns200Swml()
    {
        var svc = MakeService();
        var (status, _, body) = svc.HandleRequest("GET", "/", AuthHeader(), null);

        Assert.Equal(200, status);
        Assert.Contains("1.0.0", body);
    }

    [Fact]
    public void WrongPassword_Returns401()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("GET", "/", AuthHeader("testuser", "wrongpass"), null);
        Assert.Equal(401, status);
    }

    [Fact]
    public void WrongUser_Returns401()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("GET", "/", AuthHeader("wronguser", "testpass"), null);
        Assert.Equal(401, status);
    }

    // ------------------------------------------------------------------
    // HTTP: Security Headers
    // ------------------------------------------------------------------

    // The framework-free HandleRequest CORE returns the bare (status, headers,
    // body) triple Python's _handle_request_core returns — an EMPTY header map
    // on 200 and just {"WWW-Authenticate": "Basic"} on 401. Security /
    // Content-Type headers are the HTTP layer's concern (stamped by the
    // DispatchAsync / RunHttp adapters when actually serving), NOT baked into
    // the decision core. This keeps the decomposed dispatch byte-identical
    // across ports. The served-path security headers are covered by
    // WebServiceTests.
    [Fact]
    public void HandleRequest_200_ReturnsBareHeaders()
    {
        var svc = MakeService();
        var (status, headers, _) = svc.HandleRequest("GET", "/", AuthHeader(), null);

        Assert.Equal(200, status);
        Assert.Empty(headers);
    }

    [Fact]
    public void HandleRequest_401_ReturnsBareWwwAuthenticateAndJsonBody()
    {
        var svc = MakeService();
        var (status, headers, body) = svc.HandleRequest("GET", "/", new Dictionary<string, string>(), null);

        Assert.Equal(401, status);
        // ONLY WWW-Authenticate: Basic — no security / Content-Type headers.
        Assert.Equal("Basic", headers["WWW-Authenticate"]);
        Assert.Single(headers);
        Assert.False(headers.ContainsKey("X-Content-Type-Options"));
        // JSON error body (not plain text), matching every other port + Python.
        Assert.Contains("\"error\"", body);
        Assert.Contains("Unauthorized", body);
    }

    // ------------------------------------------------------------------
    // HTTP: /swaig and /post_prompt require auth
    // ------------------------------------------------------------------

    [Fact]
    public void Swaig_WithoutAuth_Returns401()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("POST", "/swaig", new Dictionary<string, string>(), null);
        Assert.Equal(401, status);
    }

    [Fact]
    public void Swaig_WithAuth_EmptyBody_Returns400()
    {
        // After the SWAIG lift, the endpoint validates the body. An empty
        // body with no `function` name now returns 400. The test exists to
        // prove the route is mounted under auth — 400 is the correct lifted
        // behavior; the stub-200 the old test asserted was a no-op handler.
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("POST", "/swaig", AuthHeader(), "{}");
        Assert.Equal(400, status);
    }

    [Fact]
    public void PostPrompt_WithoutAuth_Returns401()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("POST", "/post_prompt", new Dictionary<string, string>(), null);
        Assert.Equal(401, status);
    }

    [Fact]
    public void PostPrompt_WithAuth_Returns200()
    {
        var svc = MakeService();
        var (status, _, _) = svc.HandleRequest("POST", "/post_prompt", AuthHeader(), "{}");
        Assert.Equal(200, status);
    }

    // ------------------------------------------------------------------
    // HTTP: Custom Route Dispatch
    // ------------------------------------------------------------------

    [Fact]
    public void CustomRoute_SwmlDispatch()
    {
        var svc = MakeService(route: "/agent");
        svc.Verb("hangup", new Dictionary<string, object>());

        var (status, _, body) = svc.HandleRequest("GET", "/agent", AuthHeader(), null);
        Assert.Equal(200, status);
        Assert.Contains("hangup", body);
    }

    [Fact]
    public void CustomRoute_SwaigDispatch()
    {
        // Lifted handler validates body — empty body returns 400 (missing
        // function name). Point of the test: /agent/swaig routes through
        // the route prefix to HandleSwaigRequest, which it does.
        var svc = MakeService(route: "/agent");
        var (status, _, _) = svc.HandleRequest("POST", "/agent/swaig", AuthHeader(), "{}");
        Assert.Equal(400, status);
    }

    [Fact]
    public void CustomRoute_HealthStillWorks()
    {
        var svc = MakeService(route: "/agent");
        var (status, _, _) = svc.HandleRequest("GET", "/health", new Dictionary<string, string>(), null);
        Assert.Equal(200, status);
    }

    [Fact]
    public void UnmatchedRoute_Returns404()
    {
        var svc = MakeService(route: "/agent");
        var (status, _, _) = svc.HandleRequest("GET", "/other", AuthHeader(), null);
        Assert.Equal(404, status);
    }

    // ------------------------------------------------------------------
    // HTTP: Body Size Limit
    // ------------------------------------------------------------------

    [Fact]
    public void BodySizeLimit_1MBPlus1Byte_Returns413()
    {
        var svc = MakeService();
        var hugeBody = new string('x', 1_048_577); // 1MB + 1 byte
        var (status, _, _) = svc.HandleRequest("POST", "/", AuthHeader(), hugeBody);
        Assert.Equal(413, status);
    }

    // ------------------------------------------------------------------
    // SIP Username Extraction
    // ------------------------------------------------------------------

    [Fact]
    public void ExtractSipUsername_ValidUri()
    {
        var body = new Dictionary<string, object?>
        {
            ["call"] = new Dictionary<string, object?> { ["to"] = "sip:agent1@example.com" },
        };
        Assert.Equal("agent1", Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_FromTopLevelTo()
    {
        var body = new Dictionary<string, object?> { ["to"] = "sip:myuser@host.com" };
        Assert.Equal("myuser", Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_ValidChars()
    {
        var body = new Dictionary<string, object?> { ["to"] = "sip:user.name-test_1@host.com" };
        Assert.Equal("user.name-test_1", Service.ExtractSipUsername(body));
    }

    // extract_sip_username returns the extracted value VERBATIM — Python (and
    // every other port) applies NO format/length validation to the username; it
    // simply splits sip:/tel:/plain and returns the part. A SIP-username regex
    // would wrongly reject e.g. a tel: number, so no validation is applied.
    [Fact]
    public void ExtractSipUsername_UnusualChars_ReturnedVerbatim()
    {
        var body = new Dictionary<string, object?> { ["to"] = "sip:user;drop@host.com" };
        Assert.Equal("user;drop", Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_LongName_ReturnedVerbatim()
    {
        var longName = new string('a', 65);
        var body = new Dictionary<string, object?> { ["to"] = $"sip:{longName}@host.com" };
        Assert.Equal(longName, Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_TelUri_ReturnsNumber()
    {
        var body = new Dictionary<string, object?>
        {
            ["call"] = new Dictionary<string, object?> { ["to"] = "tel:+15551234567" },
        };
        Assert.Equal("+15551234567", Service.ExtractSipUsername(body));
    }

    [Fact]
    public void ExtractSipUsername_Null_ReturnsNull()
    {
        Assert.Null(Service.ExtractSipUsername(null));
    }

    [Fact]
    public void ExtractSipUsername_EmptyBody_ReturnsNull()
    {
        Assert.Null(Service.ExtractSipUsername(new Dictionary<string, object?>()));
    }

    // ------------------------------------------------------------------
    // Proxy URL
    // ------------------------------------------------------------------

    [Fact]
    public void ProxyUrl_FromEnv()
    {
        Environment.SetEnvironmentVariable("SWML_PROXY_URL_BASE", "https://proxy.example.com");
        var svc = MakeService();
        Assert.Equal("https://proxy.example.com", svc.GetProxyUrlBase());
    }

    [Fact]
    public void ProxyUrl_FromForwardedHeaders()
    {
        var svc = MakeService();
        var headers = new Dictionary<string, string>
        {
            ["X-Forwarded-Proto"] = "https",
            ["X-Forwarded-Host"] = "myapp.example.com",
        };
        Assert.Equal("https://myapp.example.com", svc.GetProxyUrlBase(headers));
    }

    [Fact]
    public void ProxyUrl_FromOriginalUrl()
    {
        var svc = MakeService();
        var headers = new Dictionary<string, string>
        {
            ["X-Original-URL"] = "https://original.example.com/path",
        };
        Assert.Equal("https://original.example.com/path", svc.GetProxyUrlBase(headers));
    }

    [Fact]
    public void ProxyUrl_Fallback()
    {
        var svc = MakeService(host: "0.0.0.0", port: 3000);
        Assert.Equal("http://0.0.0.0:3000", svc.GetProxyUrlBase());
    }

    // ------------------------------------------------------------------
    // Routing Callbacks
    // ------------------------------------------------------------------

    [Fact]
    public void RoutingCallback_Dispatched()
    {
        var svc = MakeService();
        var called = false;
        svc.RegisterRoutingCallback((data, headers) =>
        {
            called = true;
            return new Dictionary<string, object> { ["custom"] = "response" };
        }, path: "/custom");

        var (status, _, body) = svc.HandleRequest("POST", "/custom", AuthHeader(), "{}");
        Assert.True(called);
        Assert.Equal(200, status);
        Assert.Contains("response", body);
    }

    // ==================================================================
    //  SWMLService TLS derived attributes (porting-sdk d7c859d)
    //  The reference hoists four values off `self.security` in __init__:
    //    self.ssl_enabled / self.domain / self.ssl_cert_path / self.ssl_key_path
    //  Prove the .NET properties carry the SAME resolved values, including
    //  the CONFIG-FILE source (which the old env-only serve path ignored).
    // ==================================================================

    /// <summary>Repo-local scratch dir (never a machine-wide temp).</summary>
    private static string MakeScratchDir()
    {
        var root = AppContext.BaseDirectory;
        var dir = Path.Combine(root, ".sw-tmp", "swmlservice_tls_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        return dir;
    }

    [Fact]
    public void SslPropertiesDefaultToSecurityDefaults()
    {
        var svc = MakeService();
        Assert.False(svc.SslEnabled);
        Assert.Null(svc.SslCertPath);
        Assert.Null(svc.SslKeyPath);
        Assert.Null(svc.Domain);
        // They mirror `security`, exactly as the reference's __init__ does.
        Assert.Equal(svc.Security.SslEnabled, svc.SslEnabled);
        Assert.Equal(svc.Security.SslCertPath, svc.SslCertPath);
        Assert.Equal(svc.Security.SslKeyPath, svc.SslKeyPath);
        Assert.Equal(svc.Security.Domain, svc.Domain);
    }

    [Fact]
    public void SslPropertiesAreHoistedFromEnvironment()
    {
        try
        {
            Environment.SetEnvironmentVariable("SWML_SSL_ENABLED", "true");
            Environment.SetEnvironmentVariable("SWML_SSL_CERT_PATH", "/etc/ssl/env-cert.pem");
            Environment.SetEnvironmentVariable("SWML_SSL_KEY_PATH", "/etc/ssl/env-key.pem");
            Environment.SetEnvironmentVariable("SWML_DOMAIN", "env.example.com");

            var svc = MakeService();

            Assert.True(svc.SslEnabled);
            Assert.Equal("/etc/ssl/env-cert.pem", svc.SslCertPath);
            Assert.Equal("/etc/ssl/env-key.pem", svc.SslKeyPath);
            Assert.Equal("env.example.com", svc.Domain);
        }
        finally
        {
            Environment.SetEnvironmentVariable("SWML_SSL_ENABLED", null);
            Environment.SetEnvironmentVariable("SWML_SSL_CERT_PATH", null);
            Environment.SetEnvironmentVariable("SWML_SSL_KEY_PATH", null);
            Environment.SetEnvironmentVariable("SWML_DOMAIN", null);
        }
    }

    [Fact]
    public void SslPropertiesAreHoistedFromTheConfigFile()
    {
        var dir = MakeScratchDir();
        try
        {
            var configPath = Path.Combine(dir, "svc_config.json");
            File.WriteAllText(configPath,
                "{\"security\":{"
                + "\"ssl_enabled\":true,"
                + "\"ssl_cert_path\":\"/etc/ssl/file-cert.pem\","
                + "\"ssl_key_path\":\"/etc/ssl/file-key.pem\","
                + "\"domain\":\"file.example.com\""
                + "}}");

            var svc = new Service(new ServiceOptions
            {
                Name = "tls-config-service",
                BasicAuthUser = "testuser",
                BasicAuthPassword = "testpass",
                ConfigFile = configPath,
            });

            // The config file is the highest-priority source; these values are
            // what the serve path must use. Reading the environment directly
            // (as the old SslSettings.FromEnvironment did) would see none of them.
            Assert.True(svc.SslEnabled);
            Assert.Equal("/etc/ssl/file-cert.pem", svc.SslCertPath);
            Assert.Equal("/etc/ssl/file-key.pem", svc.SslKeyPath);
            Assert.Equal("file.example.com", svc.Domain);
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); }
            catch (IOException) { /* still in use */ }
            catch (UnauthorizedAccessException) { /* best effort */ }
        }
    }

    [Fact]
    public void SslPropertiesAreCallerOverridableBeforeServing()
    {
        // Mirrors the reference's serve(ssl_enabled=…, domain=…) overrides,
        // which assign onto self.ssl_enabled / self.domain.
        var svc = MakeService();
        Assert.False(svc.SslEnabled);

        svc.SslEnabled = true;
        svc.SslCertPath = "/etc/ssl/override-cert.pem";
        svc.SslKeyPath = "/etc/ssl/override-key.pem";
        svc.Domain = "override.example.com";

        Assert.True(svc.SslEnabled);
        Assert.Equal("/etc/ssl/override-cert.pem", svc.SslCertPath);
        Assert.Equal("/etc/ssl/override-key.pem", svc.SslKeyPath);
        Assert.Equal("override.example.com", svc.Domain);
    }
}
