#!/usr/bin/env python3
"""generate_example_projects.py — one runnable .csproj per shipped example.

Every shipped example is a standalone top-level-statements program, so they
cannot share a project (multiple entry points cannot co-compile). Without a
project an example is compiled by NOTHING: it is in no solution, the LINT gate's
``*.csproj`` enumeration cannot see it, and a deleted or renamed SDK symbol rots
it silently.

That is not hypothetical — it is how this repo shipped broken examples. Measured
at task #204: of 71 tracked examples across the three roots, only FOUR had a
project. 16 of the 57 under ``examples/`` no longer compiled, and all 14 under
``rest/examples/`` + ``relay/examples/`` were equally uncompiled.

This script closes the hole from both ends:

  * ``--write``  regenerates ``<Stem>.csproj`` next to every tracked example,
    one project per example, each referencing the SDK, plus a per-root
    ``Directory.Build.props``.
  * ``--check``  (the gate mode, wired as EXAMPLES-PROJECTS in run-ci.sh)
    verifies the on-disk projects are exactly the set this script would write —
    no example without a project, no project without an example, and no project
    whose content has drifted from the template. Exits non-zero naming the
    offenders.

Because ``scripts/_env.sh:dotnet_all_projects`` enumerates ``*.csproj`` off the
filesystem, having these projects automatically puts every example inside the
existing LINT gate's analyzer build (AnalysisMode=All, TreatWarningsAsErrors) —
and ``dotnet run --project <root>/<Stem>.csproj`` becomes the run target the
EXAMPLES-RUN gate drives.

    python3 scripts/generate_example_projects.py --write
    python3 scripts/generate_example_projects.py --check
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# The three example roots. These are exactly the trees the shared EXAMPLES-RUN
# gate globs (porting-sdk/scripts/examples_run.py `tracked_examples`), so the
# project coverage this script enforces matches the set that gate will try to
# run — no example is in one list and not the other.
EXAMPLE_ROOTS = ("examples", "rest/examples", "relay/examples")

# Per-example project. Mirrors the four hand-written harness projects that
# predate this script (RelayAuditHarness et al):
#   * EnableDefaultCompileItems=false + an explicit <Compile Include> so a
#     project compiles ONLY its own example rather than globbing the whole
#     directory (which would collide on the implicit Main).
# Per-project bin/obj isolation is NOT set here — it lives in the per-root
# Directory.Build.props, because BaseIntermediateOutputPath must be set
# before Microsoft.Common.props is imported (setting it in the project body
# raises MSB3539 and splits restore from build). That same props file re-imports
# the repo-root Directory.Build.props so examples keep the repo-wide analyzer bar
# (AnalysisMode=All, TreatWarningsAsErrors=true) — examples are shipping code.
TEMPLATE = """<Project Sdk="Microsoft.NET.Sdk">
  <!-- GENERATED by scripts/generate_example_projects.py; do not edit by hand.
       Regenerate with: python3 scripts/generate_example_projects.py (write mode). -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SignalWire.Examples</RootNamespace>
    <AssemblyName>{stem}</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="{stem}.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="{sdk_ref}" />
  </ItemGroup>
</Project>
"""


def tracked_examples() -> list[Path]:
    """Tracked *.cs under every example root, git-listed so untracked scratch
    files are ignored."""
    out = subprocess.run(
        ["git", "-C", str(REPO), "ls-files", *(f"{r}/*.cs" for r in EXAMPLE_ROOTS)],
        capture_output=True,
        text=True,
        check=True,
    )
    files = sorted(REPO / p for p in out.stdout.split() if p)
    return [f for f in files if f.is_file()]


def example_dirs() -> list[Path]:
    """Example roots that actually exist in this checkout."""
    return [REPO / r for r in EXAMPLE_ROOTS if (REPO / r).is_dir()]


def expected() -> dict[Path, str]:
    """Map each example's .csproj path to the exact content it should have.

    The SDK ProjectReference is relative, so its `..\\` depth follows how deep
    the example root sits (examples/ is one level, rest/examples/ is two).
    """
    out: dict[Path, str] = {}
    for f in tracked_examples():
        depth = len(f.parent.relative_to(REPO).parts)
        sdk_ref = "\\".join([".."] * depth + ["src", "SignalWire", "SignalWire.csproj"])
        out[f.with_suffix(".csproj")] = TEMPLATE.format(stem=f.stem, sdk_ref=sdk_ref)
    return out


# Per-root build defaults. Every project in an example root shares ONE directory,
# so all of them would otherwise collide on obj/ and bin/ (project.assets.json in
# particular). BaseIntermediateOutputPath MUST be set before
# Microsoft.Common.props is imported — setting it in the .csproj body raises
# MSB3539 and leaves NuGet writing the assets file to the shared obj/ while the
# build reads the per-project one. A Directory.Build.props is evaluated early
# enough, which is why this lives here and not in the generated projects.
PROPS_TEMPLATE = """<Project>

  <!-- GENERATED by scripts/generate_example_projects.py; do not edit by hand.
       Regenerate with: python3 scripts/generate_example_projects.py (write mode).

       Every .csproj in this directory is a separate single-file example program
       sharing one directory, so each gets a per-project intermediate + output
       path keyed by its own name. BaseIntermediateOutputPath has to be set
       before Microsoft.Common.props is imported (a .csproj body is too late and
       raises MSB3539), which is why it is here.

       The repo-root Directory.Build.props is imported explicitly so the analyzer
       bar (AnalysisMode=All, TreatWarningsAsErrors) still applies: examples are
       shipping code and carry the same bar as src/ and tests/. Without this
       import MSBuild would stop at THIS file and the examples would silently
       drop off the lint gate. -->

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)bin/$(MSBuildProjectName)/</BaseOutputPath>
  </PropertyGroup>

</Project>
"""


def expected_props() -> dict[Path, str]:
    """Directory.Build.props for each example root that holds an example."""
    roots = {f.parent for f in tracked_examples()}
    return {r / "Directory.Build.props": PROPS_TEMPLATE for r in roots}


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the projects")
    mode.add_argument(
        "--check", action="store_true", help="gate mode: verify, don't write"
    )
    args = ap.parse_args()

    projects = expected()
    if not projects:
        print(
            "FATAL: no tracked example *.cs found under "
            f"{', '.join(EXAMPLE_ROOTS)} — refusing to run a vacuous check. "
            "Verify the repo checkout.",
            file=sys.stderr,
        )
        return 2

    props = expected_props()
    want = {**projects, **props}
    have = {p for d in example_dirs() for p in d.glob("*.csproj")}
    have |= {
        d / "Directory.Build.props"
        for d in example_dirs()
        if (d / "Directory.Build.props").exists()
    }

    if args.write:
        for path, body in sorted(want.items()):
            if not path.exists() or path.read_text() != body:
                path.write_text(body)
        for stale in sorted(have - set(want)):
            stale.unlink()
        print(
            f"[example-projects] wrote {len(projects)} project(s) + "
            f"{len(props)} Directory.Build.props across "
            f"{', '.join(EXAMPLE_ROOTS)}"
        )
        return 0

    # --check
    missing = sorted(set(want) - have)
    extra = sorted(have - set(want))
    drifted = sorted(
        p for p, body in want.items() if p in have and p.read_text() != body
    )

    if missing:
        print(
            f"[example-projects] {len(missing)} example(s) have NO project — they are "
            f"compiled by nothing and can rot silently:"
        )
        for p in missing:
            print(f"    {p.relative_to(REPO)}  (for {p.stem}.cs)")
    if extra:
        print(
            f"[example-projects] {len(extra)} project(s) have no matching example .cs:"
        )
        for p in extra:
            print(f"    {p.relative_to(REPO)}")
    if drifted:
        print(
            f"[example-projects] {len(drifted)} project(s) drifted from the template:"
        )
        for p in drifted:
            print(f"    {p.relative_to(REPO)}")

    if missing or extra or drifted:
        print(
            "[example-projects] run: python3 scripts/generate_example_projects.py --write"
        )
        return 1

    print(
        f"[example-projects] clean — {len(projects)} example(s) across "
        f"{', '.join(EXAMPLE_ROOTS)}, each with a project."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
